### ISSUE TITLE
 Discord account can't be linked.

### ISSUE THREAD

**Issue by ghost** [marceltransier/ttt_discord_bot#3]
### Description

Discord account can't be linked.

### Steps to Reproduce

1. Install the Discord bot and let it join the server. Give it all permissions.
2. Add addon to Gmod server.
3. Type !discord jonathan, !discord 5813 or !discord jonathan#5813.

**Expected behavior:** The bot links my Discord acocunt.

**Actual behavior:** The bot gives this message. No guilde member with a discord tag like 'Jonathan' found.

**Reproduces how often:** 100 percent

**OS:** Windows

**Config:**

[Your config.json (except of the passwords and tokens)]

{
  "discord": {
    "token": "{TOKEN}",
    "guild": "299252062640799744",
    "channel": "467082100730757120"
  }
}

**Comment by Gensokian** [comment]
I just tried to reproduce the problem but couldn't in my Discord guild. Just keep in mind that the system is case sensitive!
