### ISSUE TITLE
invalid URL

### ISSUE THREAD

**Issue by Scahry** [marceltransier/ttt_discord_bot#6]
### Description

When running the Bot I now get this Error:
[TTT Discord Bot] Request to bot failed. Is the bot running?
Err: invalid url
i tried to reinstall the whole bot on my server and i still get this error

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**OS:** [On which OS runs the server?]
Windows

**Config:**

[Your config.json (except of the passwords and tokens)]

{
  "discord": {
    "token": "---",
    "guild": "---",
    "channel": "---"
  },
  "server": {
    "port": "37405"
  }
}

**Comment by timschumi** [comment]
Garry's Mod started to hard-block requests to localhost (and the entirety of all local subnets) in a recent update for whatever reason.

From the disassembly, it appears that every URL containing `://localhost`, `10.`, `172.16.`, `192.168.`, or `127.` is blocked with the error "invalid url".

One possible workaround (as far as I can see) is to add an alias for 127.0.0.1 to your system's hosts file, and setting that as the `discordbot_host`. (EDIT: There is a new launch option, `-allowlocalhttp` that removes those restrictions and is easier to setup).

Fixing this within the bot is probably not done that easily.

**Comment by Scahry** [comment]
working for me, thank you very much.

edit: working with localhost after i completely reinstalled the server

**Comment by chickenblue** [comment]
can someone explain to me what exactly I have to enter in the hosts file now? do I have to change anything in bot lua?

**Comment by timschumi** [comment]
@chickenblue You have three options:

1. Add `-allowlocalhttp` to your launch arguments. This removes the restrictions for sending HTTP requests to local IP addresses. No other changes are needed.

2. Add a line like `127.0.0.1 anycustomname` to your hosts file. You will have to replace every occurrence of `127.0.0.1`/`localhost` with `anycustomname` in the GMod addon (and its console variables).

3. Replace every occurrence of `127.0.0.1`/`localhost` with `127-0-0-1.org.uk` in the GMod addon (and its console variables). `127-0-0-1.org.uk` is a real domain (so no other modifications are required), which resolves to 127.0.0.1 when queried.

**Comment by Scahry** [comment]
after just making a new server the bot was working for me with no changes needed, no idea why.
