### ISSUE TITLE
Mute will be shown, amiright?

### ISSUE THREAD

**Issue by TheCherry** [marceltransier/ttt_discord_bot#7]
Hi,

habe den bot noch nicht versucht, aber man kann dann doch auch sehen das die Leute im Discord gemuted sind, und weiß somit das diese gestorben sind, wenn man Discord auf einem 2. Monitor oder das Layout aktiv hat, richtig?

Das würde natürlich dann nicht so gut sein.

**Comment by marceltransier** [comment]
Yes you can see if someone is muted. But you can't be sure bc the player could also mute himself.
AFAIK is there no way to hide the mute state in discord.
You can take a look at the Discord API Docs. Maybe there is a new method to achive this. Haven't used Discord for a while.
